baseurl: '/thesongsays'
exclude: ['README.md', 'node_modules', 'package.json', 'gulp.json']
artists: 
  - 
    name: Bruno Pronsato
    small: /wp-content/uploads/2010/08/artist-small-bruno.jpg
  - 
    name: Half Hawaii
    small: /wp-content/uploads/2010/09/hh_small.jpg