source: src
baseurl: '/thesongsays'
exclude: ['README.md', 'node_modules', 'package.json', 'gulp.json', 'gulpfile.js', 'dist', 'build']
artists: 
  - 
    name: Bruno Pronsato
    small: /imgs/artist-small-bruno.jpg
  - 
    name: Half Hawaii
    small: /imgs/hh_small.jpg